name: CI

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --all-features -- -D warnings          

      - name: Certificate server start
        run: |
          sh tests/integration_start.sh

      - name: Test
        run: |
          cargo check
          cargo test --all --all-features

      - name: Certificate server stop
        run: |
          sh tests/integration_stop.sh

      - name: Build
        run: |
          cargo build --all-features --release   
